name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt install mingw-w64
    - name: Make
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: setwall
        path: setwall.exe
